### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by WaluigiBSOD** [WaluigiBSOD/fzmv-password-decoder#1]
# Code

- [ ] Add the ability to decode of Jet Vermilion passwords since they are essentially the player name encrypted with some algorithm and one can be easily tell them apart from Rankings ones by looking at the length
- [x] Add a validity check for Multi-Pak Multiplayer passwords that report Synobazz Championship Circuit (can only be played in single player Championship mode)
- [x] Replace every instance of multiplication, division or remainder involving powers of 2 with their bit-wise equivalent form
- [x] In [password.js](https://github.com/WaluigiBSOD/fzmv-password-decoder/blob/13a697409277fbec92b0436f2ec2ff577d1fb2df/js/password.js#L32) the check `((((Buffer[ElementX] & (1 << BitX)) >> BitX) + ((Buffer[ElementY] & (1 << BitY)) >> BitY)) & 0x1)` can be rewritten as just `(((Buffer[ElementX] & (1 << BitX)) >> BitX) ^ ((Buffer[ElementY] & (1 << BitY)) >> BitY))`
- [x] Make constants explicit instead of using bitwise negation [in this block of 4 statements in password.js](https://github.com/WaluigiBSOD/fzmv-password-decoder/blob/13a697409277fbec92b0436f2ec2ff577d1fb2df/js/password.js#L294) 
- [x] Add an empty `.nojekyll` file in the root of the website
- [x] Add a `404.html` 404 error handler in the root of the website that redirects to the main page
